# Generated by Django 5.2.8 on 2025-11-25 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeding',
            name='oxygen',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feeding',
            name='ph',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feeding',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
