# Generated by Django 5.2.8 on 2025-12-02 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeding', '0002_feeding_oxygen_feeding_ph_feeding_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeding',
            name='feed_rate',
            field=models.FloatField(blank=True, help_text='Feed rate in grams per minute', null=True),
        ),
        migrations.AddField(
            model_name='feeding',
            name='feeder_status',
            field=models.CharField(choices=[('Idle', 'Idle'), ('Feeding', 'Feeding'), ('Error', 'Error')], default='Idle', max_length=20),
        ),
        migrations.AddField(
            model_name='feeding',
            name='recommandation',
            field=models.CharField(blank=True, choices=[('Increase Feed', 'Increase Feed'), ('Maintain Feed', 'Maintain Feed'), ('Decrease Feed', 'Decrease Feed')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='feeding',
            name='turbidity',
            field=models.FloatField(blank=True, help_text='Water turbidity in NTU', null=True),
        ),
        migrations.AlterField(
            model_name='feeding',
            name='activity_level',
            field=models.FloatField(help_text='Shrimp activity level from 0 to 1'),
        ),
        migrations.AlterField(
            model_name='feeding',
            name='oxygen',
            field=models.FloatField(blank=True, help_text='Dissolved oxygen in mg/L', null=True),
        ),
        migrations.AlterField(
            model_name='feeding',
            name='ph',
            field=models.FloatField(blank=True, help_text='pH level of the water', null=True),
        ),
        migrations.AlterField(
            model_name='feeding',
            name='temperature',
            field=models.FloatField(blank=True, help_text='Water temperature in Celsius', null=True),
        ),
    ]
