# Generated by Django 5.2.8 on 2025-12-02 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeding', '0003_feeding_feed_rate_feeding_feeder_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feeding',
            old_name='recommandation',
            new_name='recommendation',
        ),
        migrations.AlterField(
            model_name='feeding',
            name='feed_rate',
            field=models.FloatField(blank=True, help_text='Feed rate (grams/minute)', null=True),
        ),
    ]
